# Generated by Django 5.1.5 on 2025-02-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
