# Generated by Django 5.1.5 on 2025-02-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_alter_comentario_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='body_lang',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='commentable_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
