# Generated by Django 5.1.5 on 2025-01-26 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('component_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('votes_count', models.IntegerField(default=0)),
                ('title', models.JSONField()),
                ('body', models.JSONField()),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commentable_type', models.CharField(max_length=50)),
                ('commentable_id', models.BigIntegerField()),
                ('author_id', models.BigIntegerField()),
                ('body', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.proposta')),
            ],
        ),
    ]
