# Generated by Django 5.1.5 on 2025-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('component_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('votes_count', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('title_lang', models.CharField(max_length=25)),
                ('body', models.CharField(max_length=10000)),
                ('body_lang', models.CharField(max_length=25)),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
    ]
