# Generated by Django 5.1.5 on 2025-02-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
