# Generated by Django 5.1.5 on 2025-02-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0002_alter_proposta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='body',
            field=models.CharField(max_length=50000),
        ),
    ]
