# Generated by Django 5.1.5 on 2025-02-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0003_alter_proposta_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='component_id',
            field=models.IntegerField(unique=True),
        ),
    ]
