# Generated by Django 5.1.5 on 2025-02-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0004_alter_proposta_component_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='body',
            field=models.CharField(default='Proposal not found', max_length=50000),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='body_lang',
            field=models.CharField(default='--', max_length=25),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='created_at',
            field=models.DateTimeField(default='2000-01-01 00:00:00.000000'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='title',
            field=models.CharField(default='Proposal not found', max_length=1000),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='title_lang',
            field=models.CharField(default='--', max_length=25),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='updated_at',
            field=models.DateTimeField(default='2000-01-01 00:00:00.000000'),
        ),
    ]
