# Generated by Django 5.1.5 on 2025-02-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0005_alter_proposta_body_alter_proposta_body_lang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='body_lang',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='title_lang',
        ),
    ]
